# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('nazev', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('typ_organizace', models.CharField(choices=[('obec', 'Obec'), ('kulturni_dum', 'Kulturni dum'), ('poradatel', 'Poradatel')], default='obec', max_length=32)),
                ('kontaktni_email', models.EmailField(blank=True, max_length=254)),
                ('kontaktni_telefon', models.CharField(blank=True, max_length=32)),
                ('hlavni_barva', models.CharField(default='#57C7A5', max_length=7)),
                ('je_aktivni', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='ClenstviOrganizace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('vlastnik', 'Vlastnik'), ('spravce', 'Spravce'), ('pokladna', 'Pokladna'), ('odbaveni', 'Odbaveni'), ('ucetni', 'Ucetni')], max_length=32)),
                ('je_aktivni', models.BooleanField(default=True)),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clenstvi_organizaci', to=settings.AUTH_USER_MODEL)),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clenstvi', to='organizace.organizace')),
            ],
            options={
                'unique_together': {('organizace', 'uzivatel', 'role')},
            },
        ),
    ]
