# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akce', '0001_initial'),
        ('organizace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('verejne_id', models.CharField(max_length=32, unique=True)),
                ('email_zakaznika', models.EmailField(max_length=254)),
                ('jmeno_zakaznika', models.CharField(blank=True, max_length=255)),
                ('telefon_zakaznika', models.CharField(blank=True, max_length=32)),
                ('stav', models.CharField(choices=[('navrh', 'Navrh'), ('ceka_na_platbu', 'Ceka na platbu'), ('zaplaceno', 'Zaplaceno'), ('zruseno', 'Zruseno'), ('vraceno', 'Vraceno')], default='navrh', max_length=24)),
                ('mezisoucet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('poplatek', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('celkem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mena', models.CharField(default='CZK', max_length=3)),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vytvorene_objednavky', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('pocet', models.PositiveIntegerField(default=1)),
                ('cena_za_kus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_celkem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polozky_objednavky', to='akce.akce')),
                ('kategorie_vstupenky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polozky_objednavky', to='akce.kategorievstupenky')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='objednavky.objednavka')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
