# Generated by Django 5.2.9 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0002_objednavka_rezervace_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozkaobjednavky',
            name='vybrana_mista',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
