# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objednavky', '0001_initial'),
        ('organizace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('poskytovatel', models.CharField(choices=[('gopay', 'GoPay'), ('comgate', 'Comgate'), ('stripe', 'Stripe')], max_length=24)),
                ('reference_poskytovatele', models.CharField(blank=True, max_length=255)),
                ('stav', models.CharField(choices=[('vytvoreno', 'Vytvoreno'), ('ceka', 'Ceka'), ('uspesna', 'Uspesna'), ('neuspesna', 'Neuspesna'), ('vracena', 'Vracena')], default='vytvoreno', max_length=24)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mena', models.CharField(default='CZK', max_length=3)),
                ('data_poskytovatele', models.JSONField(blank=True, default=dict)),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platby', to='objednavky.objednavka')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'ordering': ['-vytvoreno'],
            },
        ),
    ]
