# Generated by Django 5.2.9 on 2026-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platba',
            name='poskytovatel',
            field=models.CharField(choices=[('gopay', 'GoPay'), ('comgate', 'Comgate'), ('stripe', 'Stripe'), ('hotovost', 'Hotovost')], max_length=24),
        ),
    ]
