# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('nazev', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('popis', models.TextField(blank=True)),
                ('zacatek', models.DateTimeField()),
                ('konec', models.DateTimeField(blank=True, null=True)),
                ('stav', models.CharField(choices=[('navrh', 'Navrh'), ('zverejneno', 'Zverejneno'), ('vyprodano', 'Vyprodano'), ('ukonceno', 'Ukonceno'), ('zruseno', 'Zruseno')], default='navrh', max_length=24)),
                ('kapacita', models.PositiveIntegerField(default=0)),
                ('je_doporucena', models.BooleanField(default=False)),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'ordering': ['zacatek'],
            },
        ),
        migrations.CreateModel(
            name='KategorieVstupenky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('nazev', models.CharField(max_length=120)),
                ('popis', models.CharField(blank=True, max_length=255)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mena', models.CharField(default='CZK', max_length=3)),
                ('kapacita', models.PositiveIntegerField(default=0)),
                ('prodej_od', models.DateTimeField(blank=True, null=True)),
                ('prodej_do', models.DateTimeField(blank=True, null=True)),
                ('je_aktivni', models.BooleanField(default=True)),
                ('akce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie_vstupenek', to='akce.akce')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'ordering': ['akce__zacatek', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='MistoKonani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('nazev', models.CharField(max_length=255)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('mesto', models.CharField(blank=True, max_length=120)),
                ('kapacita', models.PositiveIntegerField(default=0)),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
        migrations.AddField(
            model_name='akce',
            name='misto_konani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akce', to='akce.mistokonani'),
        ),
        migrations.AlterUniqueTogether(
            name='akce',
            unique_together={('organizace', 'slug')},
        ),
    ]
