# Generated by Django 5.2.9 on 2026-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akce', '0002_akce_rezervace_platnost_minuty'),
    ]

    operations = [
        migrations.AddField(
            model_name='akce',
            name='hlavni_fotka_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='akce',
            name='perex',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='akce',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
