# Generated by Django 5.2.9 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akce', '0003_akce_hlavni_fotka_url_akce_perex_akce_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistokonani',
            name='schema_sezeni',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
