# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akce', '0001_initial'),
        ('organizace', '0001_initial'),
        ('vstupenky', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odbaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('vysledek', models.CharField(choices=[('povoleno', 'Povoleno'), ('duplicitni', 'Duplicitni'), ('neplatne', 'Neplatne'), ('odmitnuto', 'Odmitnuto')], default='povoleno', max_length=24)),
                ('naskenovany_kod', models.CharField(max_length=255)),
                ('naskenovano', models.DateTimeField(auto_now_add=True)),
                ('oznaceni_zarizeni', models.CharField(blank=True, max_length=120)),
                ('akce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odbaveni', to='akce.akce')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
                ('vstupenka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbaveni', to='vstupenky.vstupenka')),
                ('zpracoval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zpracovana_odbaveni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-naskenovano'],
            },
        ),
    ]
