# Generated by Django 5.2.9 on 2026-04-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akce', '0001_initial'),
        ('objednavky', '0001_initial'),
        ('organizace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vstupenka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('kod', models.CharField(max_length=64, unique=True)),
                ('qr_data', models.CharField(max_length=255)),
                ('jmeno_navstevnika', models.CharField(blank=True, max_length=255)),
                ('email_navstevnika', models.EmailField(blank=True, max_length=254)),
                ('stav', models.CharField(choices=[('platna', 'Platna'), ('odbavena', 'Odbavena'), ('zrusena', 'Zrusena'), ('vracena', 'Vracena')], default='platna', max_length=24)),
                ('vystavena', models.DateTimeField(auto_now_add=True)),
                ('dorucena', models.DateTimeField(blank=True, null=True)),
                ('akce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vstupenky', to='akce.akce')),
                ('kategorie_vstupenky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vstupenky', to='akce.kategorievstupenky')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vstupenky', to='objednavky.objednavka')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
                ('polozka_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vstupenky', to='objednavky.polozkaobjednavky')),
                ('posledni_zmenu_stavu_provedl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zmeny_stavu_vstupenek', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vystavena'],
            },
        ),
    ]
