# Generated by Django 5.2.9 on 2026-04-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0002_objednavka_rezervace_do'),
        ('organizace', '0001_initial'),
        ('vstupenky', '0002_vstupenka_stav_rezervovana'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailovaZasilka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('prijemce_email', models.EmailField(max_length=254)),
                ('predmet', models.CharField(max_length=255)),
                ('stav', models.CharField(choices=[('vytvoreno', 'Vytvoreno'), ('odeslano', 'Odeslano'), ('chyba', 'Chyba')], default='vytvoreno', max_length=24)),
                ('text_zpravy', models.TextField(blank=True)),
                ('chyba_text', models.TextField(blank=True)),
                ('pocet_priloh', models.PositiveIntegerField(default=0)),
                ('odeslano_v', models.DateTimeField(blank=True, null=True)),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailove_zasilky', to='objednavky.objednavka')),
                ('organizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizace.organizace')),
            ],
            options={
                'ordering': ['-vytvoreno'],
            },
        ),
    ]
