# Generated by Django 5.2.9 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstupenky', '0003_emailovazasilka'),
    ]

    operations = [
        migrations.AddField(
            model_name='vstupenka',
            name='oznaceni_mista',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
